models:
  - name: shift_first
    description: 'This is an intermediary table and contains the first shift of each employee.'
    columns:
      - name: employee_id
        tests:
          - type: unique
          - type: not_null
          - type: relationship
            info:
              model: stg_employees
              column: employee_id
      - name: shift_start
        tests:
          - type: not_null
  - name: shift_hours
    description: 'This is an intermediary table and contains the shift start and end times for each shift.'
    columns:
      - name: shift
        tests:
          - type: not_null
          - type: unique
      - name: start_time
        tests:
          - type: not_null
      - name: end_time
        tests:
          - type: not_null
  - name: shift_last
    description: 'This is an intermediary table and contains the first last of each employee.'
    columns:
      - name: employee_id
        tests:
          - type: unique
          - type: not_null
          - type: relationship
            info:
              model: stg_employees
              column: employee_id
      - name: shift_end
        tests:
          - type: not_null
  - name: shifts
    description: 'This is transformation for shift and for each shift has a derive start/stop time.'
    columns:
      - name: employee_id
        tests:
          - type: not_null
          - type: relationship
            info:
              model: stg_employees
              column: employee_id
      - name: shift
        tests:
          - type: not_null
          - type: relationship
            info:
              model: shift_hours
              column: shift
      - name: shift_start
        tests:
          - type: not_null
      - name: shift_end
        tests:
          - type: not_null
  - name: shifts_by_month
    description: 'This is a transformation for shifts and contains the total number of shifts for each employee by month.'
    columns:
      - name: employee_id
        tests:
          - type: not_null
          - type: relationship
            info:
              model: stg_employees
              column: employee_id
      - name: shift_month
      - name: total_shifts
        tests:
          - type: unique
          - type: gte
            info:
              value: 0
  - name: shifts_summary
    description: 'This is final table for summary analysis of the shifts.'
    columns:
      - name: employee_id
        tests:
          - type: not_null
          - type: relationship
            info:
              model: stg_employees
              column: employee_id
      - name: first_name
      - name: last_name
      - name: first_shift
      - name: last_shift
      - name: percentage_morning_shifts
        description: 'This is the percentage number of shifts worked by the employee in the mornings.'
        tests:
          - type: gte
            info:
              value: 0
          - type: lte
            info:
              value: 100
      - name: total_shifts
        description: 'This is the total number of shifts worked by the employee.'
        tests:
          - type: gte
            info:
              value: 0
      - name: total_hours
        description: 'This is the total number of hours worked by the employee.'
        tests:
          - type: gte
            info:
              value: 0
